version: 0.0
os: linux
files:
  - source: /
    destination: cd /home/ubuntu
    overwrite: true
hooks:
  BeforeInstall:
    - location: /BeforeInstallHook.sh
  AfterInstall:
    - location: /AfterInstallHook.sh
      timeout: 300
